[mypy]
python_version = 3.12
ignore_missing_imports = True
warn_unused_ignores = False
warn_redundant_casts = True
no_implicit_optional = True
check_untyped_defs = False
exclude = (^\.venv|^docs|^data_store)

[mypy-ctg.engine.quant]
disallow_untyped_defs = False
